apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webinar-app-02
  description: For the webinar
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: daniel.gordon@harness.io
  lifecycle: experimental
